spring:
  application:
    name: gatewayserver
  config:
    import: "configserver:http://configserver-ms:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      httpclient:
        connect-timeout: 10000
        response-timeout: 3s

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true
info:
  app:
    name: "gatewayserver"
    description: "Microservices gateway"
    version: "1.0.0"

logging:
  level:
    com:
      learn:
        gatewayserver: DEBUG
resilience4j.circuitbreaker:
  configs:
    default:
      sliding-window-size: 10
      permitted-number-of-calls-in-half-open-state: 2
      failure-rate-threshold: 50
      wait-duration-in-open-state:
        seconds: 5